export const DataMen = [
  {
    id: 3,
    img: "src/assets/product-3.png",
    model: "Addidas",
    price: "$ 100",
    name: "JORDAN MARS",
    rate: 4,
  },
  {
    id: 4,
    img: "src/assets/product-4.png",
    model: "Nike",
    price: "$ 120",
    name: "Nike Sneakers",
    rate: 3,
  },
  {
    id: 6,
    img: "src/assets/product-6.png",
    model: "Nike",
    price: "$ 100",
    name: "Cosmic Unity",
    rate: 2,
  },
  {
    id: 8,
    img: "src/assets/product-8.png",
    model: "Rav",
    price: "$ 150",
    name: "RAVER WHITE",
    rate: 4,
  },
  {
    id: 10,
    img: "src/assets/product-10.png",
    model: "Rav",
    price: "$ 135",
    name: "Rav Sneakers",
    rate: 5,
  },
  {
    id: 11,
    img: "src/assets/product-11.png",
    model: "Nike",
    price: "$ 120",
    name: "Nike Vans",
    rate: 4,
  },
  {
    id: 12,
    img: "src/assets/product-12.png",
    model: "Rav",
    price: "$ 75",
    name: "Yellow Sneakers",
    rate: 1,
  },
];
